# Generated by Django 4.2.1 on 2023-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_shoe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=200),
        ),
    ]
