# Generated by Django 4.2.1 on 2023-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='shoe',
            name='imgUrl',
            field=models.TextField(default=''),
        ),
    ]
